services:
  backend:
    container_name: momentum-backend
    image: momentum-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=maselocaldev1234
      - POSTGRES_DB=momentum-db
      - JWT_SECRET=DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.
      - JWT_EXPIRY=60s
      - PORT=8091
      # Sets the timezone of the containers OS
      - TZ=Europe/Budapest
    restart: always
    ports:
      - 8091:8091
